package me.ni3cz3k4j.metaEngine.item.component;

public sealed interface MetaDeathProtectionEffect permits MetaApplyPotionDeathEffect, MetaClearEffectsDeathEffect, MetaTeleportDeathEffect, MetaHealDeathEffect, MetaExtinguishDeathEffect, MetaPlaySoundDeathEffect {}